log_level = "warn"
outputs = { Targets = ["eDP-1"] }
position = "Top"
app_launcher_cmd = "walker"
clipboard_cmd = "walker -m clipboard"
# app_launcher_cmd = "wofi --show drun"
# clipboard_cmd = "cliphist list | wofi -S dmenu | cliphist decode | wl-copy"

[modules]
left = [ [ "appLauncher", "Updates", "Workspaces" ], "MediaPlayer" ]
center = [ "WindowTitle" ]
right = [ "SystemInfo", [ "Clipboard", "Tray", "Clock", "Privacy", "notification", "Settings" ] ]

[updates]
check_cmd = "checkupdates; yay -Qua"
update_cmd = 'kitty -e bash -c "yay; echo Done - Press enter to exit; read" &'

[workspaces]
enable_workspace_filling = true

[[CustomModule]]
name = "appLauncher"
icon = ""
command = "walker"
# command = "wofi --show drun"

# [[CustomModule]]
# name = "musicVisualizer"
# icon = "󱑽"
# command = "kitty -e bash -c cava"

[[CustomModule]]
name = "notification"
icon = "󰎟"
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -t -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[window_title]
truncate_title_after_length = 100

[settings]
lock_cmd = "playerctl --all-players pause; loginctl lock-session &"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueberry"

[appearance]
style = "Islands"
scale_factor = 1.5

primary_color = "#8aadf4"
success_color = "#a6da95"
text_color = "#cad3f5"
workspace_colors = [ "#8aadf4", "#a6da95" ]
special_workspace_colors = [ "#8aadf4", "#a6da95" ]

[appearance.danger_color]
base = "#ed8796"
weak = "#eed49f"

[appearance.background_color]
base = "#24273a"
weak = "#363a4f"
strong = "#6e738d"

[appearance.secondary_color]
base = "#181926"

[appearance.menu]
opacity = 0.9
